[[IgnoredVulns]]
id = "GHSA-28wg-ghj8-5hjv"
reason = "Dev dependency in example only, not used in production"

[[IgnoredVulns]]
id = "GHSA-2v37-7h3g-55p8"
reason = "Dev dependency in example only, not used in production"

[[IgnoredVulns]]
id = "GHSA-fxqj-rqcc-2cmp"
reason = "Dev dependency in example only, not used in production"

[[IgnoredVulns]]
id = "GHSA-r28c-9q8g-f849"
reason = "Dev dependency in example only, not used in production"
