# Dependency Review Action
#
# This Action will scan dependency manifest files that change as part of a Pull Request,
# surfacing known-vulnerable versions of the packages declared or updated in the PR.
# Once installed, if the workflow run is marked as required,
# PRs introducing known-vulnerable packages will be blocked from merging.
#
# Source repository: https://github.com/actions/dependency-review-action
name: 'Dependency Review'
on:
  pull_request:
    paths-ignore:
      - 'examples/**/package-lock.json'

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - name: 'Checkout Repository'
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@2031cfc080254a8a887f58cffee85186f0e49e48 # v4.9.0
        with:
          allow-ghsas: >-
            GHSA-hvx9-hwr7-wjj9,
            GHSA-8h8q-6873-q5fj,
            GHSA-36qx-fr4f-26g5,
            GHSA-267c-6grr-h53f,
            GHSA-492v-c6pp-mqqv,
            GHSA-c4j6-fc7j-m34r,
            GHSA-mg66-mrh9-m8jx,
            GHSA-26hh-7cqf-hhc6,
            GHSA-wfc6-r584-vfw7,
            GHSA-h64f-5h5j-jqjh,
            GHSA-gx5p-jg67-6x7h,
            GHSA-ffhc-5mcf-pf4q,
            GHSA-vfv6-92ff-j949,
            GHSA-3g8h-86w9-wvmq
