name: example-quiet
on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests with `quiet` parameter
      - name: Cypress run
        uses: ./ # if copying, replace with step-security/cypress-io-github-action@v7
        with:
          working-directory: examples/quiet
          quiet: true
