name: example-chrome
# In the example jobs, the action is called with
# uses: ./
# which runs the action code from the current branch.
# If you copy this workflow to another repo, replace the line with
# uses: step-security/cypress-io-github-action@v7
on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-24.04
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Chrome headless
        uses: ./
        with:
          # Print information about the system and current environment
          # including detected browsers
          # which are pre-installed in GitHub-hosted runners
          # see https://on.cypress.io/command-line#cypress-info
          # We do not need the build parameter to build an app here
          # because the remote https://example.cypress.io site
          # is already built and running, and so for convenience
          # we repurpose the build parameter to get cypress info instead.
          build: npx cypress info
          working-directory: examples/browser
          browser: chrome
          summary-title: 'Chrome headless'

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: screenshots-headless-chrome
          path: examples/browser/cypress/screenshots

      - run: npx image-size cypress/screenshots/**/*.png
        working-directory: examples/browser

      - name: Chrome headed
        uses: ./
        with:
          # Cypress and dependencies are already installed
          install: false
          working-directory: examples/browser
          browser: chrome
          headed: true
          summary-title: 'Chrome headed'

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: screenshots-headed-chrome
          path: examples/browser/cypress/screenshots

      - run: npx image-size cypress/screenshots/**/*.png
        working-directory: examples/browser
