name: example-debug
# This workflow demonstrates how to use the DEBUG environment variable to get debug output.
#
# In the example jobs, the action is called with
# uses: ./
# which runs the action code from the current branch.
# If you copy this workflow to another repo, replace the line with
# uses: step-security/cypress-io-github-action@v7
on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:
  action-debug:
    runs-on: ubuntu-24.04
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Cypress action debug logs
        uses: ./
        env:
          # This enables debug logging output for the action
          DEBUG: '@step-security/cypress-io-github-action'
        with:
          working-directory: examples/basic

  cypress-debug:
    runs-on: ubuntu-24.04
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Cypress debug logs
        uses: ./
        env:
          # This enables debug logging output for Cypress
          # See https://on.cypress.io/troubleshooting#Log-sources for other filtered DEBUG values
          DEBUG: 'cypress:*'
        with:
          working-directory: examples/basic

        # You can also combine the two debug options into one line
        # to get both action debug and Cypress debug output
        # DEBUG: '@step-security/cypress-io-github-action, cypress:*'

  install-binary-debug:
    runs-on: ubuntu-24.04
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Cypress npm install
        # Install only the Cypress npm module
        uses: ./
        with:
          working-directory: examples/basic
          runTests: false
        env:
          # Skip the Cypress binary installation
          CYPRESS_INSTALL_BINARY: 0

      - name: Cypress binary install
        # Now install the Cypress binary with debug enabled
        uses: ./
        with:
          working-directory: examples/basic
          # use --force option to override any cached Cypress binary version
          command: npx cypress install --force
        env:
          DEBUG: 'cypress:cli*'
