name: example-basic-pnpm
on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:
  basic-pnpm:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - windows-2025
          - macos-26
    runs-on: ${{ matrix.os }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

        # See https://github.com/pnpm/action-setup
      - name: Install pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0
        with:
          version: 10

        # See https://github.com/actions/setup-node
      - name: Install Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: '.node-version'
          cache: pnpm
          cache-dependency-path: examples/basic-pnpm/pnpm-lock.yaml

      - name: Cypress tests
        uses: ./ # if copying, replace with step-security/cypress-io-github-action@v7
        with:
          package-manager-cache: false
          working-directory: examples/basic-pnpm
          # print information about detected browsers, etc
          # see https://on.cypress.io/command-line#cypress-info
          build: pnpm exec cypress info
