name: example-firefox
on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

jobs:
  firefox:
    runs-on: ubuntu-24.04
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Firefox
        uses: ./ # if copying, replace with step-security/cypress-io-github-action@v7
        timeout-minutes: 3
        with:
          # let's show browser and system info
          build: npx cypress info
          working-directory: examples/browser
          browser: firefox

      # report screenshot size and store the screenshots as test artifacts
      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: screenshots-in-firefox
          path: examples/browser/cypress/screenshots

      - run: npx image-size cypress/screenshots/**/*.png
        working-directory: examples/browser
