name: example-custom-command
# example using the command parameter
# this allows any cli command to be run
# the command parameter causes other action parameters that would be passed to Cypress
# to be ignored and so it should not be used with these other parameters
# for example, browsers, config, record, parallel, spec, etc would be ignored
on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  start:
    runs-on: ubuntu-24.04
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Custom tests
        uses: ./ # if copying, replace with step-security/cypress-io-github-action@v7
        with:
          command: npm run custom-test
          working-directory: examples/custom-command

      - name: Show saved file
        run: cat examples/custom-command/results.json
